version: "3.8"

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atk-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - atk-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: atk-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - atk-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: atk-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - atk-network

networks:
  atk-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
