version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: atk-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - atk-network

  webserver:
    image: nginx:alpine
    container_name: atk-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/prod:/etc/nginx/conf.d/
      - ./docker/nginx/ssl:/etc/nginx/ssl/
    networks:
      - atk-network

  db:
    image: mysql:8.0
    container_name: atk-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - atk-network

networks:
  atk-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
